# ========================================
# Prod 環境 — Binance Futures 正式環境
# ========================================
# 正式 API Key 申請: https://www.binance.com → API 管理
# API 文件: https://developers.binance.com/docs/derivatives/

binance:
  futures:
#    base-url: https://fapi.binance.com
#    ws-base-url: wss://fstream.binance.com/ws/
    base-url: https://testnet.binancefuture.com
    ws-base-url: wss://testnet.binancefuture.com/ws/


# logging 設定由 logback-spring.xml 統一管理
